import { ILang } from "./interface";
export const enUS: ILang = {
  back: "Back",
  cancel: "Cancel",
  clear: "Clear",
  confirm: "Confirm",
  defaultLabel: "Default label",
  httpRequired: "Required",
  inputIsDisabled: "Input is disabled",
  inputManually: "Input manually",
  loading: "Loading",
  ng: "NG",
  noCandidates: "No items",
  noData: "No data",
  nothingToSelect: "Nothing to select",
  ok: "OK",
  pickNow: "Pick now",
  pleaseAddDigits: "Please add digits",
  pleaseInput: "Please input",
  pleaseSelect: "Please select",
  required: "Required",
  save: "Save",
  search: "Search",
  submit: "Submit",
  xCandidates: "{x} items to select",
};
