import { ILang } from "./interface";
export const zhCN: ILang = {
  back: "返回",
  cancel: "取消",
  clear: "清除",
  confirm: "确认",
  defaultLabel: "默认标签",
  httpRequired: "必填",
  inputIsDisabled: "输入框被禁用",
  inputManually: "手动输入",
  loading: "加载中",
  ng: "不合格",
  noCandidates: "没有可选项",
  noData: "没有数据",
  nothingToSelect: "没有可选项",
  ok: "合格",
  pickNow: "定位到现在",
  pleaseAddDigits: "请输入数字",
  pleaseInput: "请输入",
  pleaseSelect: "请选择",
  required: "必填",
  save: "保存",
  search: "搜索",
  submit: "提交",
  xCandidates: "{x} 个可选项",
};
